language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: build
  on:
    branch: main
